title: "Total Pest Control"
url: "https://total-pest-control-chicago.github.io"
baseurl: "/new-total-pest-control-website"

defaults:
  - scope:
      path: ""
    values:
      layout: default
      body_class: index-page

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
