title: "Total Pest Control"
url: "https://www.totalpestcontrol.us"
baseurl: "https://total-pest-control-chicago.github.io/new-total-pest-control-website/"

defaults:
  - scope:
      path: ""
    values:
      layout: default
      body_class: index-page

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
